server {
    listen 80;
    # En pro cambiar este localhost por el dominio (ej: moyete.dev)
    server_name rnoguer.com;

    root /usr/share/nginx/html;
    index index.html index.html;

    # Enrutamiento para SPA de React (soluciona el error 404 al hacer F5)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverso para desviar las peticiones del chat al backend de FastAPI
    location /api/ {
        proxy_pass http://backend.railway.internal:8000; # Tenemos que apuntar al nombre de dominio interno de railway, apuntando al otro contenedor donde tenemos el back (backend.railway.internal)
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
